//
// Broker.cpp — Named pipe broker server implementation.
//
// The broker executes sandboxed operations under a medium-IL LUA token.
// All file and registry operations use ntdll directly, so the hook DLL can
// pass raw NT parameters without any Win32/NT conversion on its side.
// NT→Win32 path conversion happens once here, only for policy matching.
//

#include <cstdio>
#include <thread>
#include "Broker.h"
#include "RBoxMessage.h"
#include "utils/TokenUtils.h"

// ============================================================================
// NT Native Types and ntdll Function Pointers
// ============================================================================

#ifndef NTSTATUS
typedef LONG NTSTATUS;
#endif

#define NT_SUCCESS(s)   ((NTSTATUS)(s) >= 0)
#define OBJ_CASE_INSENSITIVE 0x00000040UL

// NT status codes used in broker responses
#ifndef STATUS_SUCCESS
#define STATUS_SUCCESS               ((NTSTATUS)0x00000000L)
#define STATUS_UNSUCCESSFUL          ((NTSTATUS)0xC0000001L)
#define STATUS_INVALID_HANDLE        ((NTSTATUS)0xC0000008L)
#define STATUS_INVALID_PARAMETER     ((NTSTATUS)0xC000000DL)
#define STATUS_NO_MEMORY             ((NTSTATUS)0xC0000017L)
#define STATUS_ACCESS_DENIED         ((NTSTATUS)0xC0000022L)
#define STATUS_OBJECT_NAME_INVALID   ((NTSTATUS)0xC0000033L)
#define STATUS_OBJECT_NAME_NOT_FOUND ((NTSTATUS)0xC0000034L)
#define STATUS_OBJECT_PATH_NOT_FOUND ((NTSTATUS)0xC000003AL)
#endif

// Map common Win32 error codes to NTSTATUS equivalents for broker responses
// generated by Win32 API failures (ImpersonateLoggedOnUser, DuplicateHandle, etc.).
static NTSTATUS BrokerWin32ToNtStatus(DWORD err) {
    switch (err) {
        case ERROR_SUCCESS:           return STATUS_SUCCESS;
        case ERROR_ACCESS_DENIED:     return STATUS_ACCESS_DENIED;
        case ERROR_INVALID_PARAMETER: return STATUS_INVALID_PARAMETER;
        case ERROR_NOT_ENOUGH_MEMORY: return STATUS_NO_MEMORY;
        case ERROR_INVALID_HANDLE:    return STATUS_INVALID_HANDLE;
        case ERROR_FILE_NOT_FOUND:    return STATUS_OBJECT_NAME_NOT_FOUND;
        case ERROR_PATH_NOT_FOUND:    return STATUS_OBJECT_PATH_NOT_FOUND;
        default:                      return STATUS_UNSUCCESSFUL;
    }
}

typedef struct _BROKER_UNICODE_STRING {
    USHORT  Length;
    USHORT  MaximumLength;
    PWSTR   Buffer;
} BROKER_UNICODE_STRING;

typedef struct _BROKER_OBJECT_ATTRIBUTES {
    ULONG                   Length;
    HANDLE                  RootDirectory;
    BROKER_UNICODE_STRING*  ObjectName;
    ULONG                   Attributes;
    PVOID                   SecurityDescriptor;
    PVOID                   SecurityQualityOfService;
} BROKER_OBJECT_ATTRIBUTES;

typedef struct _BROKER_IO_STATUS_BLOCK {
    union { NTSTATUS Status; PVOID Pointer; };
    ULONG_PTR Information;
} BROKER_IO_STATUS_BLOCK;

typedef struct _BROKER_FILE_NETWORK_OPEN_INFORMATION {
    LARGE_INTEGER CreationTime;
    LARGE_INTEGER LastAccessTime;
    LARGE_INTEGER LastWriteTime;
    LARGE_INTEGER ChangeTime;
    LARGE_INTEGER AllocationSize;
    LARGE_INTEGER EndOfFile;
    ULONG         FileAttributes;
} BROKER_FILE_NETWORK_OPEN_INFORMATION;

typedef struct _BROKER_KEY_VALUE_PARTIAL_INFORMATION {
    ULONG TitleIndex;
    ULONG Type;
    ULONG DataLength;
    UCHAR Data[1];
} BROKER_KEY_VALUE_PARTIAL_INFORMATION;

#define KeyValuePartialInformationBroker 2

static void BrokerInitUnicodeString(BROKER_UNICODE_STRING* pUs, LPCWSTR szStr) {
    USHORT len = szStr ? (USHORT)(wcslen(szStr) * sizeof(WCHAR)) : 0;
    pUs->Length        = len;
    pUs->MaximumLength = len + sizeof(WCHAR);
    pUs->Buffer        = (PWSTR)szStr;
}

#define BROKER_INIT_OA(pOa, pName, attrs)                       \
    do {                                                        \
        (pOa)->Length                   = sizeof(BROKER_OBJECT_ATTRIBUTES); \
        (pOa)->RootDirectory            = nullptr;              \
        (pOa)->ObjectName               = (pName);              \
        (pOa)->Attributes               = (attrs);              \
        (pOa)->SecurityDescriptor       = nullptr;              \
        (pOa)->SecurityQualityOfService = nullptr;              \
    } while (0)

typedef NTSTATUS (NTAPI *pfnBrokerNtCreateFile)(
    PHANDLE, ACCESS_MASK, BROKER_OBJECT_ATTRIBUTES*, BROKER_IO_STATUS_BLOCK*,
    LARGE_INTEGER*, ULONG, ULONG, ULONG, ULONG, PVOID, ULONG);

typedef NTSTATUS (NTAPI *pfnBrokerNtDeleteFile)(BROKER_OBJECT_ATTRIBUTES*);

typedef NTSTATUS (NTAPI *pfnBrokerNtQueryFullAttributesFile)(
    BROKER_OBJECT_ATTRIBUTES*, BROKER_FILE_NETWORK_OPEN_INFORMATION*);

typedef NTSTATUS (NTAPI *pfnBrokerNtOpenKeyEx)(
    PHANDLE, ACCESS_MASK, BROKER_OBJECT_ATTRIBUTES*, ULONG /*OpenOptions*/);

typedef NTSTATUS (NTAPI *pfnBrokerNtCreateKey)(
    PHANDLE, ACCESS_MASK, BROKER_OBJECT_ATTRIBUTES*, ULONG /*TitleIndex*/,
    BROKER_UNICODE_STRING* /*Class*/, ULONG /*CreateOptions*/, PULONG /*Disposition*/);

typedef NTSTATUS (NTAPI *pfnBrokerNtQueryValueKey)(
    HANDLE, BROKER_UNICODE_STRING*, ULONG, PVOID, ULONG, PULONG);

typedef NTSTATUS (NTAPI *pfnBrokerNtSetValueKey)(
    HANDLE, BROKER_UNICODE_STRING*, ULONG, ULONG, PVOID, ULONG);

typedef ULONG (NTAPI *pfnBrokerRtlNtStatusToDosError)(NTSTATUS);

static pfnBrokerNtCreateFile              s_NtCreateFile              = nullptr;
static pfnBrokerNtDeleteFile              s_NtDeleteFile              = nullptr;
static pfnBrokerNtQueryFullAttributesFile s_NtQueryFullAttributesFile = nullptr;
static pfnBrokerNtOpenKeyEx               s_NtOpenKeyEx               = nullptr;
static pfnBrokerNtCreateKey               s_NtCreateKey               = nullptr;
static pfnBrokerNtQueryValueKey           s_NtQueryValueKey           = nullptr;
static pfnBrokerNtSetValueKey             s_NtSetValueKey             = nullptr;
static pfnBrokerRtlNtStatusToDosError     s_RtlNtStatusToDosError     = nullptr;

static DWORD NtToDosError(NTSTATUS status) {
    if (status == 0) return ERROR_SUCCESS;
    return s_RtlNtStatusToDosError ? s_RtlNtStatusToDosError(status) : ERROR_GEN_FAILURE;
}

// ============================================================================
// Policy Path Helpers — NT namespace to Win32 format, for regex matching only
// ============================================================================

// Strips \??\ / \DosDevices\ / \??\\UNC\ prefix so policy patterns can use
// the familiar Win32 form (e.g. "C:\\Users\\.*").
static BOOL NtPathToWin32ForPolicy(LPCWSTR szNtPath, LPWSTR szOut, DWORD cchOut) {
    if (!szNtPath || !szNtPath[0] || !szOut || cchOut == 0)
        return FALSE;

    DWORD nLen = (DWORD)wcslen(szNtPath);

    // \??\UNC\server\share  →  \\server\share
    if (nLen >= 8 && _wcsnicmp(szNtPath, L"\\??\\UNC\\", 8) == 0) {
        DWORD n = nLen - 6; // keep two leading backslashes
        if (n >= cchOut) return FALSE;
        szOut[0] = L'\\'; szOut[1] = L'\\';
        wcsncpy_s(szOut + 2, cchOut - 2, szNtPath + 8, nLen - 8);
        return TRUE;
    }
    // \??\ prefix  →  Win32 drive path
    if (nLen >= 4 && wcsncmp(szNtPath, L"\\??\\", 4) == 0) {
        DWORD n = nLen - 4;
        if (n >= cchOut) return FALSE;
        wcsncpy_s(szOut, cchOut, szNtPath + 4, n);
        szOut[n] = L'\0';
        return TRUE;
    }
    // \DosDevices\UNC\  →  double backslashes (\\)
    if (nLen >= 16 && _wcsnicmp(szNtPath, L"\\DosDevices\\UNC\\", 16) == 0) {
        DWORD n = nLen - 14;
        if (n >= cchOut) return FALSE;
        szOut[0] = L'\\'; szOut[1] = L'\\';
        wcsncpy_s(szOut + 2, cchOut - 2, szNtPath + 16, nLen - 16);
        return TRUE;
    }
    // \DosDevices\  →  Win32 drive path
    if (nLen >= 12 && _wcsnicmp(szNtPath, L"\\DosDevices\\", 12) == 0) {
        DWORD n = nLen - 12;
        if (n >= cchOut) return FALSE;
        wcsncpy_s(szOut, cchOut, szNtPath + 12, n);
        szOut[n] = L'\0';
        return TRUE;
    }
    return FALSE;
}

// Converts NT registry path to Win32-style hive\subkey for policy matching.
// \Registry\Machine\X  →  HKLM\X
// \Registry\User\X     →  HKU\X
static BOOL NtRegPathToWin32ForPolicy(LPCWSTR szNtPath, LPWSTR szOut, DWORD cchOut) {
    if (!szNtPath) return FALSE;
    DWORD nLen = (DWORD)wcslen(szNtPath);

    struct { LPCWSTR prefix; DWORD prefLen; LPCWSTR hive; DWORD hiveLen; } maps[] = {
        { L"\\Registry\\Machine\\", 18, L"HKLM\\", 5 },
        { L"\\Registry\\User\\",    15, L"HKU\\",  4 },
    };
    for (auto& m : maps) {
        if (nLen > m.prefLen && _wcsnicmp(szNtPath, m.prefix, m.prefLen) == 0) {
            DWORD subLen = nLen - m.prefLen;
            if (m.hiveLen + subLen >= cchOut) return FALSE;
            wcscpy_s(szOut, cchOut, m.hive);
            wcsncpy_s(szOut + m.hiveLen, cchOut - m.hiveLen, szNtPath + m.prefLen, subLen);
            szOut[m.hiveLen + subLen] = L'\0';
            return TRUE;
        }
    }
    return FALSE;
}

static void LogBrokerFailure(const char* operation, const char* stage, LPCWSTR target, DWORD status) {
    char msg[512];
    sprintf_s(msg, "Broker: %s %s target=%ls status=%lu", operation, stage,
              target ? target : L"<null>", status);
    IssueMessage(msg, status == ERROR_SUCCESS ? MSGTYPE_INFO :
                      status == ERROR_ACCESS_DENIED ? MSGTYPE_WARNING : MSGTYPE_ERROR);
}

// ============================================================================
// Construction / Destruction
// ============================================================================

Broker::Broker()
    : m_hBrokerToken(nullptr)
    , m_pSD(nullptr)
    , m_pDacl(nullptr)
    , m_pSacl(nullptr)
    , m_pLogonIdSid(nullptr)
    , m_hShutdownEvent(nullptr)
{
    ZeroMemory(m_szPipeName, sizeof(m_szPipeName));
    ZeroMemory(&m_sa, sizeof(m_sa));
}

Broker::~Broker() {
    Stop();
}

// ============================================================================
// Public API
// ============================================================================

DWORD Broker::Initialize(HANDLE hAdminToken) {
    DWORD fStatus;

    m_hShutdownEvent = CreateEvent(nullptr, TRUE, FALSE, nullptr);
    if (!m_hShutdownEvent)
        return GetLastError();

    if ((fStatus = ExtractLogonIdSid(hAdminToken)) != ERROR_SUCCESS)
        return fStatus;

    if ((fStatus = CreateBrokerToken(hAdminToken)) != ERROR_SUCCESS)
        return fStatus;

    if ((fStatus = GeneratePipeName()) != ERROR_SUCCESS)
        return fStatus;

    if ((fStatus = BuildPipeSecurity()) != ERROR_SUCCESS)
        return fStatus;

    // Load ntdll functions used by the operation handlers
    HMODULE hNtdll = GetModuleHandleW(L"ntdll.dll");
    if (!hNtdll)
        return ERROR_MOD_NOT_FOUND;

    s_NtCreateFile              = (pfnBrokerNtCreateFile)             GetProcAddress(hNtdll, "NtCreateFile");
    s_NtDeleteFile              = (pfnBrokerNtDeleteFile)             GetProcAddress(hNtdll, "NtDeleteFile");
    s_NtQueryFullAttributesFile = (pfnBrokerNtQueryFullAttributesFile)GetProcAddress(hNtdll, "NtQueryFullAttributesFile");
    s_NtOpenKeyEx               = (pfnBrokerNtOpenKeyEx)              GetProcAddress(hNtdll, "NtOpenKeyEx");
    s_NtCreateKey               = (pfnBrokerNtCreateKey)              GetProcAddress(hNtdll, "NtCreateKey");
    s_NtQueryValueKey           = (pfnBrokerNtQueryValueKey)          GetProcAddress(hNtdll, "NtQueryValueKey");
    s_NtSetValueKey             = (pfnBrokerNtSetValueKey)            GetProcAddress(hNtdll, "NtSetValueKey");
    s_RtlNtStatusToDosError     = (pfnBrokerRtlNtStatusToDosError)    GetProcAddress(hNtdll, "RtlNtStatusToDosError");

    if (!s_NtCreateFile || !s_NtDeleteFile || !s_NtQueryFullAttributesFile ||
        !s_NtOpenKeyEx || !s_NtCreateKey || !s_NtQueryValueKey || !s_NtSetValueKey ||
        !s_RtlNtStatusToDosError) {
        IssueMessage("Broker: Failed to resolve ntdll exports", MSGTYPE_ERROR);
        return ERROR_PROC_NOT_FOUND;
    }

    // Try to load policy from file next to the executable
    WCHAR szExePath[MAX_PATH];
    GetModuleFileName(nullptr, szExePath, MAX_PATH);
    // Replace the exe filename with policy.conf
    WCHAR* pSlash = wcsrchr(szExePath, L'\\');
    if (pSlash) {
        wcscpy_s(pSlash + 1, MAX_PATH - (pSlash + 1 - szExePath), L"policy.conf");
        if (m_policy.LoadFromFile(szExePath) != ERROR_SUCCESS) {
            IssueMessage("Broker: No policy.conf found, using defaults", MSGTYPE_INFO);
            m_policy.LoadDefaults();
        } else {
            IssueMessage("Broker: Loaded policy from policy.conf", MSGTYPE_INFO);
        }
    } else {
        m_policy.LoadDefaults();
    }

    char msg[256];
    sprintf(msg, "Broker: Initialized, pipe name: %ls", m_szPipeName);
    IssueMessage(msg, MSGTYPE_INFO);

    return ERROR_SUCCESS;
}

DWORD Broker::Start() {
    std::thread listener(ListenerThreadProc, this);
    listener.detach();

    IssueMessage("Broker: Listener started", MSGTYPE_INFO);
    return ERROR_SUCCESS;
}

DWORD Broker::Stop() {
    if (m_hShutdownEvent) {
        SetEvent(m_hShutdownEvent);
        // Give threads time to notice and clean up
        Sleep(500);
    }

    if (m_hBrokerToken)   { CloseHandle(m_hBrokerToken); m_hBrokerToken = nullptr; }
    if (m_pSD)            { LocalFree(m_pSD);   m_pSD = nullptr; }
    if (m_pDacl)          { LocalFree(m_pDacl); m_pDacl = nullptr; }
    if (m_pSacl)          { LocalFree(m_pSacl); m_pSacl = nullptr; }
    if (m_pLogonIdSid)    { LocalFree(m_pLogonIdSid); m_pLogonIdSid = nullptr; }
    if (m_hShutdownEvent) { CloseHandle(m_hShutdownEvent); m_hShutdownEvent = nullptr; }

    return ERROR_SUCCESS;
}

LPCWSTR Broker::GetPipeName() const {
    return m_szPipeName;
}

BrokerPolicy& Broker::GetPolicy() {
    return m_policy;
}

// ============================================================================
// Token Creation
// ============================================================================

DWORD Broker::CreateBrokerToken(HANDLE hAdminToken) {
    HANDLE hDupToken = nullptr;

    if (!DuplicateTokenEx(hAdminToken, TOKEN_ALL_ACCESS, nullptr,
                          SecurityImpersonation, TokenPrimary, &hDupToken))
        return GetLastError();

    // LUA_TOKEN produces the UAC-filtered standard-user token:
    // admin groups become deny-only, dangerous privileges removed.
    if (!CreateRestrictedToken(hDupToken, LUA_TOKEN,
                               0, nullptr, 0, nullptr, 0, nullptr,
                               &m_hBrokerToken)) {
        DWORD err = GetLastError();
        CloseHandle(hDupToken);
        return err;
    }

    CloseHandle(hDupToken);

    // Set to Medium IL — the "normal" user integrity level
    DWORD fStatus = SetTokenMediumIL(m_hBrokerToken);
    if (fStatus != ERROR_SUCCESS) {
        CloseHandle(m_hBrokerToken);
        m_hBrokerToken = nullptr;
    }

    return fStatus;
}

// ============================================================================
// LogonID SID Extraction
// ============================================================================

DWORD Broker::ExtractLogonIdSid(HANDLE hToken) {
    DWORD dwSize = 0;

    // Get required buffer size
    GetTokenInformation(hToken, TokenGroups, nullptr, 0, &dwSize);
    if (GetLastError() != ERROR_INSUFFICIENT_BUFFER)
        return GetLastError();

    auto pGroups = (PTOKEN_GROUPS)malloc(dwSize);
    if (!pGroups)
        return ERROR_NOT_ENOUGH_MEMORY;

    if (!GetTokenInformation(hToken, TokenGroups, pGroups, dwSize, &dwSize)) {
        DWORD err = GetLastError();
        free(pGroups);
        return err;
    }

    DWORD fStatus = ERROR_NOT_FOUND;

    for (DWORD i = 0; i < pGroups->GroupCount; i++) {
        if ((pGroups->Groups[i].Attributes & SE_GROUP_LOGON_ID) == SE_GROUP_LOGON_ID) {
            PSID pSrc = pGroups->Groups[i].Sid;
            DWORD dwSidLen = GetLengthSid(pSrc);

            m_pLogonIdSid = (PSID)LocalAlloc(LPTR, dwSidLen);
            if (!m_pLogonIdSid) {
                fStatus = ERROR_NOT_ENOUGH_MEMORY;
                break;
            }

            if (!CopySid(dwSidLen, m_pLogonIdSid, pSrc)) {
                fStatus = GetLastError();
                LocalFree(m_pLogonIdSid);
                m_pLogonIdSid = nullptr;
                break;
            }

            fStatus = ERROR_SUCCESS;
            break;
        }
    }

    free(pGroups);
    return fStatus;
}

// ============================================================================
// Pipe Name Generation
// ============================================================================

DWORD Broker::GeneratePipeName() {
    HCRYPTPROV hProv = 0;
    BYTE randomBytes[8];

    if (!CryptAcquireContext(&hProv, nullptr, nullptr, PROV_RSA_FULL, CRYPT_VERIFYCONTEXT))
        return GetLastError();

    if (!CryptGenRandom(hProv, sizeof(randomBytes), randomBytes)) {
        DWORD err = GetLastError();
        CryptReleaseContext(hProv, 0);
        return err;
    }
    CryptReleaseContext(hProv, 0);

    WCHAR szHex[17] = {};
    for (int i = 0; i < 8; i++)
        swprintf_s(szHex + i * 2, 3, L"%02X", randomBytes[i]);

    swprintf_s(m_szPipeName, _countof(m_szPipeName),
               L"%s%lu_%s", BROKER_PIPE_PREFIX, GetCurrentProcessId(), szHex);

    return ERROR_SUCCESS;
}

// ============================================================================
// Pipe Security Descriptor
// ============================================================================

DWORD Broker::BuildPipeSecurity() {
    PSID pLowILSid = nullptr;
    DWORD fStatus = ERROR_SUCCESS;

    if (!ConvertStringSidToSid(LOW_IL_STRING_SID, &pLowILSid))
        return GetLastError();

    // Build DACL: grant LogonID SID read+write access
    {
        DWORD dwDaclSize = sizeof(ACL)
            + sizeof(ACCESS_ALLOWED_ACE) - sizeof(DWORD) + GetLengthSid(m_pLogonIdSid);

        m_pDacl = (PACL)LocalAlloc(LPTR, dwDaclSize);
        if (!m_pDacl) { fStatus = ERROR_NOT_ENOUGH_MEMORY; goto Cleanup; }

        if (!InitializeAcl(m_pDacl, dwDaclSize, ACL_REVISION))
            { fStatus = GetLastError(); goto Cleanup; }

        if (!AddAccessAllowedAce(m_pDacl, ACL_REVISION,
                                 FILE_GENERIC_READ | FILE_GENERIC_WRITE,
                                 m_pLogonIdSid))
            { fStatus = GetLastError(); goto Cleanup; }
    }

    // Build SACL: Low mandatory integrity label
    {
        DWORD dwSaclSize = sizeof(ACL)
            + sizeof(SYSTEM_MANDATORY_LABEL_ACE) - sizeof(DWORD) + GetLengthSid(pLowILSid);

        m_pSacl = (PACL)LocalAlloc(LPTR, dwSaclSize);
        if (!m_pSacl) { fStatus = ERROR_NOT_ENOUGH_MEMORY; goto Cleanup; }

        if (!InitializeAcl(m_pSacl, dwSaclSize, ACL_REVISION))
            { fStatus = GetLastError(); goto Cleanup; }

        if (!AddMandatoryAce(m_pSacl, ACL_REVISION, 0,
                             SYSTEM_MANDATORY_LABEL_NO_WRITE_UP | SYSTEM_MANDATORY_LABEL_NO_READ_UP,
                             pLowILSid))
            { fStatus = GetLastError(); goto Cleanup; }
    }

    // Assemble security descriptor
    {
        m_pSD = (PSECURITY_DESCRIPTOR)LocalAlloc(LPTR, SECURITY_DESCRIPTOR_MIN_LENGTH);
        if (!m_pSD) { fStatus = ERROR_NOT_ENOUGH_MEMORY; goto Cleanup; }

        if (!InitializeSecurityDescriptor(m_pSD, SECURITY_DESCRIPTOR_REVISION))
            { fStatus = GetLastError(); goto Cleanup; }

        if (!SetSecurityDescriptorDacl(m_pSD, TRUE, m_pDacl, FALSE))
            { fStatus = GetLastError(); goto Cleanup; }

        if (!SetSecurityDescriptorSacl(m_pSD, TRUE, m_pSacl, FALSE))
            { fStatus = GetLastError(); goto Cleanup; }

        m_sa.nLength = sizeof(SECURITY_ATTRIBUTES);
        m_sa.lpSecurityDescriptor = m_pSD;
        m_sa.bInheritHandle = FALSE;
    }

Cleanup:
    if (pLowILSid) LocalFree(pLowILSid);
    return fStatus;
}

// ============================================================================
// Pipe Instance Creation
// ============================================================================

HANDLE Broker::CreatePipeInstance() {
    return CreateNamedPipe(
        m_szPipeName,
        PIPE_ACCESS_DUPLEX | FILE_FLAG_OVERLAPPED,
        PIPE_TYPE_MESSAGE | PIPE_READMODE_MESSAGE | PIPE_WAIT,
        PIPE_UNLIMITED_INSTANCES,
        BROKER_PIPE_BUFFER_SIZE,
        BROKER_PIPE_BUFFER_SIZE,
        0,
        &m_sa);
}

// ============================================================================
// Listener Thread
// ============================================================================

void Broker::ListenerThreadProc(Broker* pBroker) {
    while (true) {
        HANDLE hPipe = pBroker->CreatePipeInstance();
        if (hPipe == INVALID_HANDLE_VALUE) {
            char msg[128];
            sprintf(msg, "Broker: CreateNamedPipe failed with error %lu", GetLastError());
            IssueMessage(msg, MSGTYPE_ERROR);
            return;
        }

        OVERLAPPED ov = {};
        ov.hEvent = CreateEvent(nullptr, TRUE, FALSE, nullptr);

        BOOL bConnected = ConnectNamedPipe(hPipe, &ov);
        DWORD dwErr = GetLastError();

        if (!bConnected && dwErr == ERROR_IO_PENDING) {
            HANDLE waitHandles[2] = { ov.hEvent, pBroker->m_hShutdownEvent };
            DWORD dwWait = WaitForMultipleObjects(2, waitHandles, FALSE, INFINITE);

            if (dwWait == WAIT_OBJECT_0 + 1) {
                // Shutdown signaled
                CancelIo(hPipe);
                CloseHandle(ov.hEvent);
                CloseHandle(hPipe);
                return;
            }
        } else if (!bConnected && dwErr != ERROR_PIPE_CONNECTED) {
            CloseHandle(ov.hEvent);
            CloseHandle(hPipe);
            continue;
        }

        CloseHandle(ov.hEvent);

        IssueMessage("Broker: Client connected", MSGTYPE_INFO);

        std::thread clientThread(ClientThreadProc, pBroker, hPipe);
        clientThread.detach();
    }
}

// ============================================================================
// Client Handler Thread
// ============================================================================

void Broker::ClientThreadProc(Broker* pBroker, HANDLE hPipe) {
    BYTE requestBuf[BROKER_MAX_MESSAGE_SIZE];
    BYTE responseBuf[BROKER_MAX_MESSAGE_SIZE];

    while (WaitForSingleObject(pBroker->m_hShutdownEvent, 0) != WAIT_OBJECT_0) {
        // Overlapped read
        OVERLAPPED ov = {};
        ov.hEvent = CreateEvent(nullptr, TRUE, FALSE, nullptr);

        DWORD dwBytesRead = 0;
        BOOL bRead = ReadFile(hPipe, requestBuf, sizeof(requestBuf), &dwBytesRead, &ov);
        DWORD dwErr = GetLastError();

        if (!bRead && dwErr == ERROR_IO_PENDING) {
            HANDLE waitHandles[2] = { ov.hEvent, pBroker->m_hShutdownEvent };
            DWORD dwWait = WaitForMultipleObjects(2, waitHandles, FALSE, INFINITE);

            if (dwWait == WAIT_OBJECT_0 + 1) {
                CancelIo(hPipe);
                CloseHandle(ov.hEvent);
                break;
            }

            if (!GetOverlappedResult(hPipe, &ov, &dwBytesRead, FALSE)) {
                CloseHandle(ov.hEvent);
                break;
            }
        } else if (!bRead) {
            CloseHandle(ov.hEvent);
            break;
        }

        CloseHandle(ov.hEvent);

        if (dwBytesRead < sizeof(BrokerMessageHeader))
            continue;

        // Dispatch
        DWORD dwResponseSize = 0;
        pBroker->DispatchRequest(requestBuf, dwBytesRead,
                                 responseBuf, sizeof(responseBuf),
                                 dwResponseSize);

        // Overlapped write
        OVERLAPPED ovWrite = {};
        ovWrite.hEvent = CreateEvent(nullptr, TRUE, FALSE, nullptr);
        DWORD dwBytesWritten = 0;
        WriteFile(hPipe, responseBuf, dwResponseSize, &dwBytesWritten, &ovWrite);
        GetOverlappedResult(hPipe, &ovWrite, &dwBytesWritten, TRUE);
        CloseHandle(ovWrite.hEvent);
    }

    FlushFileBuffers(hPipe);
    DisconnectNamedPipe(hPipe);
    CloseHandle(hPipe);
}

// ============================================================================
// Request Dispatch
// ============================================================================

DWORD Broker::DispatchRequest(const BYTE* pRequestBuf, DWORD dwRequestSize,
                              BYTE* pResponseBuf, DWORD dwResponseBufSize,
                              DWORD& dwResponseSize) {
    auto* pHeader = reinterpret_cast<const BrokerMessageHeader*>(pRequestBuf);
    const BYTE* pPayload = pRequestBuf + sizeof(BrokerMessageHeader);
    DWORD dwPayloadSize = dwRequestSize - sizeof(BrokerMessageHeader);

    // Prepare default error response
    auto* pRespHeader = reinterpret_cast<BrokerResponseHeader*>(pResponseBuf);
    pRespHeader->dwTotalSize = sizeof(BrokerResponseHeader);
    pRespHeader->dwRequestId = pHeader->dwRequestId;
    pRespHeader->dwStatus = (DWORD)STATUS_ACCESS_DENIED;
    pRespHeader->dwHandle = 0;
    dwResponseSize = sizeof(BrokerResponseHeader);

    switch (static_cast<BrokerOperation>(pHeader->dwOperation)) {
        case BROKER_OP_PING:
            return HandlePing(pHeader->dwRequestId, pResponseBuf, dwResponseBufSize, dwResponseSize);

        case BROKER_OP_OPEN_FILE:
            return HandleOpenFile(pPayload, dwPayloadSize, pHeader->dwRequestId,
                                  pHeader->dwProcessId, pResponseBuf, dwResponseBufSize, dwResponseSize);

        case BROKER_OP_DELETE_FILE:
            return HandleDeleteFile(pPayload, dwPayloadSize, pHeader->dwRequestId,
                                    pResponseBuf, dwResponseBufSize, dwResponseSize);

        case BROKER_OP_QUERY_FILE:
            return HandleQueryFile(pPayload, dwPayloadSize, pHeader->dwRequestId,
                                   pResponseBuf, dwResponseBufSize, dwResponseSize);

        case BROKER_OP_OPEN_REG:
            return HandleOpenReg(pPayload, dwPayloadSize, pHeader->dwRequestId,
                                 pHeader->dwProcessId, pResponseBuf, dwResponseBufSize, dwResponseSize);

        case BROKER_OP_QUERY_REG:
            return HandleQueryReg(pPayload, dwPayloadSize, pHeader->dwRequestId,
                                  pResponseBuf, dwResponseBufSize, dwResponseSize);

        case BROKER_OP_WRITE_REG:
            return HandleWriteReg(pPayload, dwPayloadSize, pHeader->dwRequestId,
                                  pResponseBuf, dwResponseBufSize, dwResponseSize);

        case BROKER_OP_CREATE_REG:
            return HandleCreateReg(pPayload, dwPayloadSize, pHeader->dwRequestId,
                                   pHeader->dwProcessId, pResponseBuf, dwResponseBufSize, dwResponseSize);

        case BROKER_OP_OPEN_PROCESS:
            return HandleOpenProcess(pPayload, dwPayloadSize, pHeader->dwRequestId,
                                     pHeader->dwProcessId, pResponseBuf, dwResponseBufSize, dwResponseSize);

        case BROKER_OP_TRACE:
            return HandleTrace(pPayload, dwPayloadSize, pHeader->dwRequestId,
                               pHeader->dwProcessId, pResponseBuf, dwResponseBufSize, dwResponseSize);

        default:
            return ERROR_INVALID_FUNCTION;
    }
}

// ============================================================================
// Payload Validation Helper
// ============================================================================

// Validates that szNtPath is a non-empty, null-terminated NT path within the
// payload bounds, then extracts it.  Returns FALSE on any parse failure.
static BOOL ValidateNtPath(const WCHAR* szNtPath, DWORD dwPathLengthBytes,
                            DWORD dwPayloadSize, DWORD dwFixedSize) {
    if (dwPathLengthBytes < sizeof(WCHAR))
        return FALSE;
    if (dwPathLengthBytes > dwPayloadSize - dwFixedSize)
        return FALSE;
    DWORD chars = dwPathLengthBytes / sizeof(WCHAR);
    if (szNtPath[chars - 1] != L'\0')
        return FALSE;
    return TRUE;
}

// ============================================================================
// Operation Handlers
// ============================================================================

DWORD Broker::HandlePing(DWORD dwRequestId, BYTE* pResp, DWORD, DWORD& dwRespSize) {
    auto* pRespHeader = reinterpret_cast<BrokerResponseHeader*>(pResp);
    pRespHeader->dwTotalSize = sizeof(BrokerResponseHeader);
    pRespHeader->dwRequestId = dwRequestId;
    pRespHeader->dwStatus    = ERROR_SUCCESS;
    pRespHeader->dwHandle    = 0;
    dwRespSize = sizeof(BrokerResponseHeader);
    return ERROR_SUCCESS;
}

DWORD Broker::HandleOpenFile(const BYTE* pPayload, DWORD dwPayloadSize, DWORD dwRequestId,
                             DWORD dwCallerPid, BYTE* pResp, DWORD, DWORD& dwRespSize) {
    auto* pRespHeader = reinterpret_cast<BrokerResponseHeader*>(pResp);

    // Validate payload
    if (dwPayloadSize < offsetof(OpenFileRequestPayload, szNtPath))
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    auto* pReq = reinterpret_cast<const OpenFileRequestPayload*>(pPayload);

    if (!ValidateNtPath(pReq->szNtPath, pReq->dwPathLengthBytes, dwPayloadSize,
                        offsetof(OpenFileRequestPayload, szNtPath)))
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    LPCWSTR szNtPath = pReq->szNtPath;

    // Policy check: convert NT path to Win32 format (for regex matching only)
    WCHAR szWin32Path[MAX_PATH];
    if (!NtPathToWin32ForPolicy(szNtPath, szWin32Path, MAX_PATH))
        { pRespHeader->dwStatus = (DWORD)STATUS_OBJECT_NAME_INVALID; return ERROR_BAD_PATHNAME; }

    if (!m_policy.IsAllowed(BROKER_OP_OPEN_FILE, szWin32Path)) {
        pRespHeader->dwStatus = (DWORD)STATUS_ACCESS_DENIED;
        LogBrokerFailure("OPEN_FILE", "policy denied", szWin32Path, ERROR_ACCESS_DENIED);
        return ERROR_ACCESS_DENIED;
    }

    // Build OBJECT_ATTRIBUTES from the raw NT path
    BROKER_UNICODE_STRING uPath;
    BrokerInitUnicodeString(&uPath, szNtPath);
    BROKER_OBJECT_ATTRIBUTES oa;
    BROKER_INIT_OA(&oa, &uPath, pReq->ObjAttributes | OBJ_CASE_INSENSITIVE);

    LARGE_INTEGER allocSize;
    allocSize.QuadPart = pReq->AllocationSize;

    BROKER_IO_STATUS_BLOCK iosb = {};
    HANDLE hFile = nullptr;

    // Impersonate and open
    if (!ImpersonateLoggedOnUser(m_hBrokerToken))
        { pRespHeader->dwStatus = (DWORD)BrokerWin32ToNtStatus(GetLastError()); return pRespHeader->dwStatus; }

    NTSTATUS ntStatus = s_NtCreateFile(
        &hFile, pReq->DesiredAccess, &oa, &iosb,
        pReq->AllocationSize ? &allocSize : nullptr,
        pReq->FileAttributes ? pReq->FileAttributes : FILE_ATTRIBUTE_NORMAL,
        pReq->ShareAccess,
        pReq->CreateDisposition,
        pReq->CreateOptions,
        nullptr, 0);

    RevertToSelf();

    DWORD fStatus = NtToDosError(ntStatus);
    if (fStatus != ERROR_SUCCESS) {
        pRespHeader->dwStatus = (DWORD)ntStatus;
        // LogBrokerFailure("OPEN_FILE", "NtCreateFile failed", szNtPath, fStatus);
        return fStatus;
    }

    // Duplicate handle into caller's process
    HANDLE hCallerProcess = OpenProcess(PROCESS_DUP_HANDLE, FALSE, dwCallerPid);
    if (!hCallerProcess) {
        fStatus = GetLastError();
        CloseHandle(hFile);
        pRespHeader->dwStatus = (DWORD)BrokerWin32ToNtStatus(fStatus);
        // LogBrokerFailure("OPEN_FILE", "OpenProcess caller failed", szNtPath, fStatus);
        return fStatus;
    }

    HANDLE hDup = nullptr;
    if (!DuplicateHandle(GetCurrentProcess(), hFile, hCallerProcess, &hDup,
                         0, FALSE, DUPLICATE_SAME_ACCESS))
        fStatus = GetLastError();

    CloseHandle(hFile);
    CloseHandle(hCallerProcess);

    LogBrokerFailure("OPEN_FILE", fStatus == ERROR_SUCCESS ? "policy allowed" : "DuplicateHandle failed",
                     szWin32Path, fStatus);

    pRespHeader->dwTotalSize = sizeof(BrokerResponseHeader) + sizeof(OpenFileResponsePayload);
    pRespHeader->dwRequestId = dwRequestId;
    pRespHeader->dwStatus    = (DWORD)BrokerWin32ToNtStatus(fStatus);
    pRespHeader->dwHandle    = (DWORD_PTR)hDup;

    auto* pRespPayload = reinterpret_cast<OpenFileResponsePayload*>(pResp + sizeof(BrokerResponseHeader));
    pRespPayload->Information = (DWORD64)iosb.Information;
    dwRespSize = sizeof(BrokerResponseHeader) + sizeof(OpenFileResponsePayload);

    return fStatus;
}

DWORD Broker::HandleDeleteFile(const BYTE* pPayload, DWORD dwPayloadSize, DWORD dwRequestId,
                               BYTE* pResp, DWORD, DWORD& dwRespSize) {
    auto* pRespHeader = reinterpret_cast<BrokerResponseHeader*>(pResp);

    // Validate payload
    if (dwPayloadSize < offsetof(DeleteFileRequestPayload, szNtPath))
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    auto* pReq = reinterpret_cast<const DeleteFileRequestPayload*>(pPayload);

    if (!ValidateNtPath(pReq->szNtPath, pReq->dwPathLengthBytes, dwPayloadSize,
                        offsetof(DeleteFileRequestPayload, szNtPath)))
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    LPCWSTR szNtPath = pReq->szNtPath;

    WCHAR szWin32Path[MAX_PATH];
    if (!NtPathToWin32ForPolicy(szNtPath, szWin32Path, MAX_PATH))
        { pRespHeader->dwStatus = (DWORD)STATUS_OBJECT_NAME_INVALID; return ERROR_BAD_PATHNAME; }

    if (!m_policy.IsAllowed(BROKER_OP_DELETE_FILE, szWin32Path)) {
        pRespHeader->dwStatus = (DWORD)STATUS_ACCESS_DENIED;
        // LogBrokerFailure("DELETE_FILE", "policy denied", szWin32Path, ERROR_ACCESS_DENIED);
        return ERROR_ACCESS_DENIED;
    }

    BROKER_UNICODE_STRING uPath;
    BrokerInitUnicodeString(&uPath, szNtPath);
    BROKER_OBJECT_ATTRIBUTES oa;
    BROKER_INIT_OA(&oa, &uPath, pReq->ObjAttributes | OBJ_CASE_INSENSITIVE);

    // Impersonate and delete
    if (!ImpersonateLoggedOnUser(m_hBrokerToken))
        { pRespHeader->dwStatus = (DWORD)BrokerWin32ToNtStatus(GetLastError()); return pRespHeader->dwStatus; }

    NTSTATUS ntStatus = s_NtDeleteFile(&oa);

    RevertToSelf();

    DWORD fStatus = NtToDosError(ntStatus);

    pRespHeader->dwTotalSize = sizeof(BrokerResponseHeader);
    pRespHeader->dwRequestId = dwRequestId;
    pRespHeader->dwStatus    = (DWORD)ntStatus;
    pRespHeader->dwHandle    = 0;
    dwRespSize = sizeof(BrokerResponseHeader);

    return fStatus;
}

DWORD Broker::HandleQueryFile(const BYTE* pPayload, DWORD dwPayloadSize, DWORD dwRequestId,
                              BYTE* pResp, DWORD, DWORD& dwRespSize) {
    auto* pRespHeader = reinterpret_cast<BrokerResponseHeader*>(pResp);

    // Validate payload
    if (dwPayloadSize < offsetof(QueryFileRequestPayload, szNtPath))
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    auto* pReq = reinterpret_cast<const QueryFileRequestPayload*>(pPayload);

    if (!ValidateNtPath(pReq->szNtPath, pReq->dwPathLengthBytes, dwPayloadSize,
                        offsetof(QueryFileRequestPayload, szNtPath)))
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    LPCWSTR szNtPath = pReq->szNtPath;

    WCHAR szWin32Path[MAX_PATH];
    if (!NtPathToWin32ForPolicy(szNtPath, szWin32Path, MAX_PATH))
        { pRespHeader->dwStatus = (DWORD)STATUS_OBJECT_NAME_INVALID; return ERROR_BAD_PATHNAME; }

    if (!m_policy.IsAllowed(BROKER_OP_QUERY_FILE, szWin32Path)) {
        pRespHeader->dwStatus = (DWORD)STATUS_ACCESS_DENIED;
        // LogBrokerFailure("QUERY_FILE", "policy denied", szWin32Path, ERROR_ACCESS_DENIED);
        return ERROR_ACCESS_DENIED;
    }

    BROKER_UNICODE_STRING uPath;
    BrokerInitUnicodeString(&uPath, szNtPath);
    BROKER_OBJECT_ATTRIBUTES oa;
    BROKER_INIT_OA(&oa, &uPath, pReq->ObjAttributes | OBJ_CASE_INSENSITIVE);

    BROKER_FILE_NETWORK_OPEN_INFORMATION info = {};

    // Impersonate and query
    if (!ImpersonateLoggedOnUser(m_hBrokerToken))
        { pRespHeader->dwStatus = (DWORD)BrokerWin32ToNtStatus(GetLastError()); return pRespHeader->dwStatus; }

    NTSTATUS ntStatus = s_NtQueryFullAttributesFile(&oa, &info);

    RevertToSelf();

    DWORD fStatus = NtToDosError(ntStatus);

    pRespHeader->dwTotalSize = sizeof(BrokerResponseHeader);
    pRespHeader->dwRequestId = dwRequestId;
    pRespHeader->dwStatus    = (DWORD)ntStatus;
    pRespHeader->dwHandle    = 0;

    if (fStatus == ERROR_SUCCESS) {
        auto* pRespPayload = reinterpret_cast<QueryFileResponsePayload*>(
            pResp + sizeof(BrokerResponseHeader));
        pRespPayload->CreationTime   = info.CreationTime.QuadPart;
        pRespPayload->LastAccessTime = info.LastAccessTime.QuadPart;
        pRespPayload->LastWriteTime  = info.LastWriteTime.QuadPart;
        pRespPayload->ChangeTime     = info.ChangeTime.QuadPart;
        pRespPayload->AllocationSize = info.AllocationSize.QuadPart;
        pRespPayload->EndOfFile      = info.EndOfFile.QuadPart;
        pRespPayload->FileAttributes = info.FileAttributes;
        pRespPayload->_pad           = 0;
        dwRespSize = sizeof(BrokerResponseHeader) + sizeof(QueryFileResponsePayload);
        pRespHeader->dwTotalSize = dwRespSize;
    } else {
        dwRespSize = sizeof(BrokerResponseHeader);
    }

    return fStatus;
}

DWORD Broker::HandleOpenReg(const BYTE* pPayload, DWORD dwPayloadSize, DWORD dwRequestId,
                            DWORD dwCallerPid, BYTE* pResp, DWORD, DWORD& dwRespSize) {
    auto* pRespHeader = reinterpret_cast<BrokerResponseHeader*>(pResp);

    // Validate payload
    if (dwPayloadSize < offsetof(OpenRegRequestPayload, szNtPath))
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    auto* pReq = reinterpret_cast<const OpenRegRequestPayload*>(pPayload);

    if (!ValidateNtPath(pReq->szNtPath, pReq->dwPathLengthBytes, dwPayloadSize,
                        offsetof(OpenRegRequestPayload, szNtPath)))
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    LPCWSTR szNtPath = pReq->szNtPath;

    // Policy check using the full NT registry path → Win32 hive format
    WCHAR szWin32Path[512];
    if (!NtRegPathToWin32ForPolicy(szNtPath, szWin32Path, _countof(szWin32Path)))
        { pRespHeader->dwStatus = (DWORD)STATUS_OBJECT_NAME_INVALID; return ERROR_BAD_PATHNAME; }

    if (!m_policy.IsAllowed(BROKER_OP_OPEN_REG, szWin32Path)) {
        pRespHeader->dwStatus = (DWORD)STATUS_ACCESS_DENIED;
        // LogBrokerFailure("OPEN_REG", "policy denied", szWin32Path, ERROR_ACCESS_DENIED);
        return ERROR_ACCESS_DENIED;
    }

    BROKER_UNICODE_STRING uPath;
    BrokerInitUnicodeString(&uPath, szNtPath);
    BROKER_OBJECT_ATTRIBUTES oa;
    BROKER_INIT_OA(&oa, &uPath, pReq->ObjAttributes | OBJ_CASE_INSENSITIVE);

    HANDLE hKey = nullptr;

    // Impersonate and open
    if (!ImpersonateLoggedOnUser(m_hBrokerToken))
        { pRespHeader->dwStatus = (DWORD)BrokerWin32ToNtStatus(GetLastError()); return pRespHeader->dwStatus; }

    NTSTATUS ntStatus = s_NtOpenKeyEx(&hKey, pReq->DesiredAccess, &oa, pReq->OpenOptions);

    RevertToSelf();

    DWORD fStatus = NtToDosError(ntStatus);
    if (fStatus != ERROR_SUCCESS) {
        pRespHeader->dwStatus = (DWORD)ntStatus;
        // LogBrokerFailure("OPEN_REG", "NtOpenKey failed", szWin32Path, fStatus);
        return fStatus;
    }

    // Duplicate the key handle into the caller's process
    HANDLE hCallerProcess = OpenProcess(PROCESS_DUP_HANDLE, FALSE, dwCallerPid);
    if (!hCallerProcess) {
        fStatus = GetLastError();
        CloseHandle(hKey);
        pRespHeader->dwStatus = (DWORD)BrokerWin32ToNtStatus(fStatus);
        // LogBrokerFailure("OPEN_REG", "OpenProcess caller failed", szWin32Path, fStatus);
        return fStatus;
    }

    HANDLE hDup = nullptr;
    if (!DuplicateHandle(GetCurrentProcess(), hKey, hCallerProcess, &hDup,
                         0, FALSE, DUPLICATE_SAME_ACCESS))
        fStatus = GetLastError();

    CloseHandle(hKey);
    CloseHandle(hCallerProcess);

    pRespHeader->dwTotalSize = sizeof(BrokerResponseHeader);
    pRespHeader->dwRequestId = dwRequestId;
    pRespHeader->dwStatus    = (DWORD)BrokerWin32ToNtStatus(fStatus);
    pRespHeader->dwHandle    = (DWORD_PTR)hDup;
    dwRespSize = sizeof(BrokerResponseHeader);

    return fStatus;
}

DWORD Broker::HandleQueryReg(const BYTE* pPayload, DWORD dwPayloadSize, DWORD dwRequestId,
                             BYTE* pResp, DWORD dwRespBufSize, DWORD& dwRespSize) {
    auto* pRespHeader = reinterpret_cast<BrokerResponseHeader*>(pResp);

    // Validate payload
    if (dwPayloadSize < offsetof(QueryRegRequestPayload, szData))
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    auto* pReq = reinterpret_cast<const QueryRegRequestPayload*>(pPayload);

    // Extract NT registry path and value name from the packed data
    DWORD dwPathChars      = pReq->dwPathLengthBytes / sizeof(WCHAR);
    DWORD dwValueNameChars = pReq->dwValueNameLengthBytes / sizeof(WCHAR);
    DWORD dwTotalChars     = dwPathChars + dwValueNameChars;
    DWORD dwAvailChars     = (dwPayloadSize - offsetof(QueryRegRequestPayload, szData)) / sizeof(WCHAR);

    if (dwTotalChars > dwAvailChars || dwPathChars == 0 || dwValueNameChars == 0)
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    LPCWSTR szNtPath    = pReq->szData;
    LPCWSTR szValueName = pReq->szData + dwPathChars;

    if (szNtPath[dwPathChars - 1] != L'\0' || szValueName[dwValueNameChars - 1] != L'\0')
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    WCHAR szWin32Path[512];
    if (!NtRegPathToWin32ForPolicy(szNtPath, szWin32Path, _countof(szWin32Path)))
        { pRespHeader->dwStatus = (DWORD)STATUS_OBJECT_NAME_INVALID; return ERROR_BAD_PATHNAME; }

    if (!m_policy.IsAllowed(BROKER_OP_QUERY_REG, szWin32Path)) {
        pRespHeader->dwStatus = (DWORD)STATUS_ACCESS_DENIED;
        // LogBrokerFailure("QUERY_REG", "policy denied", szWin32Path, ERROR_ACCESS_DENIED);
        return ERROR_ACCESS_DENIED;
    }

    BROKER_UNICODE_STRING uPath;
    BrokerInitUnicodeString(&uPath, szNtPath);
    BROKER_OBJECT_ATTRIBUTES oa;
    BROKER_INIT_OA(&oa, &uPath, pReq->ObjAttributes | OBJ_CASE_INSENSITIVE);

    BROKER_UNICODE_STRING uValue;
    BrokerInitUnicodeString(&uValue, szValueName);

    // Buffer for KEY_VALUE_PARTIAL_INFORMATION + data
    BYTE partBuf[8192];
    ULONG cbResult = 0;
    HANDLE hKey = nullptr;
    NTSTATUS ntStatus;

    // Impersonate, open key, query value
    if (!ImpersonateLoggedOnUser(m_hBrokerToken))
        { pRespHeader->dwStatus = (DWORD)BrokerWin32ToNtStatus(GetLastError()); return pRespHeader->dwStatus; }

    ntStatus = s_NtOpenKeyEx(&hKey, KEY_QUERY_VALUE, &oa, 0);
    if (NT_SUCCESS(ntStatus)) {
        ntStatus = s_NtQueryValueKey(hKey, &uValue, KeyValuePartialInformationBroker,
                                     partBuf, sizeof(partBuf), &cbResult);
        CloseHandle(hKey);
    }

    RevertToSelf();

    DWORD fStatus = NtToDosError(ntStatus);

    pRespHeader->dwTotalSize = sizeof(BrokerResponseHeader);
    pRespHeader->dwRequestId = dwRequestId;
    pRespHeader->dwStatus    = (DWORD)ntStatus;
    pRespHeader->dwHandle    = 0;

    if (fStatus == ERROR_SUCCESS) {
        auto* pPartInfo    = reinterpret_cast<BROKER_KEY_VALUE_PARTIAL_INFORMATION*>(partBuf);
        auto* pRespPayload = reinterpret_cast<QueryRegResponsePayload*>(
            pResp + sizeof(BrokerResponseHeader));

        pRespPayload->dwRegType  = pPartInfo->Type;
        pRespPayload->dwDataSize = pPartInfo->DataLength;
        memcpy(pRespPayload->data, pPartInfo->Data, pPartInfo->DataLength);

        dwRespSize = sizeof(BrokerResponseHeader)
                   + offsetof(QueryRegResponsePayload, data)
                   + pPartInfo->DataLength;
        pRespHeader->dwTotalSize = dwRespSize;
    } else {
        dwRespSize = sizeof(BrokerResponseHeader);
    }

    return fStatus;
}

DWORD Broker::HandleWriteReg(const BYTE* pPayload, DWORD dwPayloadSize, DWORD dwRequestId,
                             BYTE* pResp, DWORD, DWORD& dwRespSize) {
    auto* pRespHeader = reinterpret_cast<BrokerResponseHeader*>(pResp);

    // Validate payload
    if (dwPayloadSize < offsetof(WriteRegRequestPayload, szData))
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    auto* pReq = reinterpret_cast<const WriteRegRequestPayload*>(pPayload);

    DWORD dwPathChars      = pReq->dwPathLengthBytes / sizeof(WCHAR);
    DWORD dwValueNameChars = pReq->dwValueNameLengthBytes / sizeof(WCHAR);
    DWORD dwMinPayload     = offsetof(WriteRegRequestPayload, szData)
                           + pReq->dwPathLengthBytes + pReq->dwValueNameLengthBytes + pReq->dwDataSize;

    if (dwPayloadSize < dwMinPayload || dwPathChars == 0 || dwValueNameChars == 0)
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    LPCWSTR szNtPath    = pReq->szData;
    LPCWSTR szValueName = pReq->szData + dwPathChars;
    const BYTE* pData   = reinterpret_cast<const BYTE*>(pReq->szData + dwPathChars + dwValueNameChars);

    if (szNtPath[dwPathChars - 1] != L'\0' || szValueName[dwValueNameChars - 1] != L'\0')
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    WCHAR szWin32Path[512];
    if (!NtRegPathToWin32ForPolicy(szNtPath, szWin32Path, _countof(szWin32Path)))
        { pRespHeader->dwStatus = (DWORD)STATUS_OBJECT_NAME_INVALID; return ERROR_BAD_PATHNAME; }

    if (!m_policy.IsAllowed(BROKER_OP_WRITE_REG, szWin32Path)) {
        pRespHeader->dwStatus = (DWORD)STATUS_ACCESS_DENIED;
        // LogBrokerFailure("WRITE_REG", "policy denied", szWin32Path, ERROR_ACCESS_DENIED);
        return ERROR_ACCESS_DENIED;
    }

    BROKER_UNICODE_STRING uPath;
    BrokerInitUnicodeString(&uPath, szNtPath);
    BROKER_OBJECT_ATTRIBUTES oa;
    BROKER_INIT_OA(&oa, &uPath, pReq->ObjAttributes | OBJ_CASE_INSENSITIVE);

    BROKER_UNICODE_STRING uValue;
    BrokerInitUnicodeString(&uValue, szValueName);

    HANDLE hKey = nullptr;
    NTSTATUS ntStatus;

    // Impersonate, open key, set value
    if (!ImpersonateLoggedOnUser(m_hBrokerToken))
        { pRespHeader->dwStatus = (DWORD)BrokerWin32ToNtStatus(GetLastError()); return pRespHeader->dwStatus; }

    ntStatus = s_NtOpenKeyEx(&hKey, KEY_SET_VALUE, &oa, 0);
    if (NT_SUCCESS(ntStatus)) {
        ntStatus = s_NtSetValueKey(hKey, &uValue, 0, pReq->dwRegType,
                                   (PVOID)pData, pReq->dwDataSize);
        CloseHandle(hKey);
    }

    RevertToSelf();

    DWORD fStatus = NtToDosError(ntStatus);

    pRespHeader->dwTotalSize = sizeof(BrokerResponseHeader);
    pRespHeader->dwRequestId = dwRequestId;
    pRespHeader->dwStatus    = (DWORD)ntStatus;
    pRespHeader->dwHandle    = 0;
    dwRespSize = sizeof(BrokerResponseHeader);

    return fStatus;
}

DWORD Broker::HandleCreateReg(const BYTE* pPayload, DWORD dwPayloadSize, DWORD dwRequestId,
                               DWORD dwCallerPid, BYTE* pResp, DWORD, DWORD& dwRespSize) {
    auto* pRespHeader = reinterpret_cast<BrokerResponseHeader*>(pResp);

    // Validate payload
    if (dwPayloadSize < offsetof(CreateRegRequestPayload, szData))
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    auto* pReq = reinterpret_cast<const CreateRegRequestPayload*>(pPayload);

    DWORD dwPathChars  = pReq->dwPathLengthBytes / sizeof(WCHAR);
    DWORD dwClassChars = pReq->dwClassLengthBytes / sizeof(WCHAR);
    DWORD dwTotalChars = dwPathChars + dwClassChars;
    DWORD dwAvailChars = (dwPayloadSize - offsetof(CreateRegRequestPayload, szData)) / sizeof(WCHAR);

    if (dwTotalChars > dwAvailChars || dwPathChars == 0)
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    LPCWSTR szNtPath = pReq->szData;
    if (szNtPath[dwPathChars - 1] != L'\0')
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    LPCWSTR szClass = nullptr;
    if (dwClassChars > 0) {
        szClass = pReq->szData + dwPathChars;
        if (szClass[dwClassChars - 1] != L'\0')
            { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }
    }

    // Policy check using the full NT registry path → Win32 hive format
    WCHAR szWin32Path[512];
    if (!NtRegPathToWin32ForPolicy(szNtPath, szWin32Path, _countof(szWin32Path)))
        { pRespHeader->dwStatus = (DWORD)STATUS_OBJECT_NAME_INVALID; return ERROR_BAD_PATHNAME; }

    if (!m_policy.IsAllowed(BROKER_OP_CREATE_REG, szWin32Path)) {
        pRespHeader->dwStatus = (DWORD)STATUS_ACCESS_DENIED;
        return ERROR_ACCESS_DENIED;
    }

    BROKER_UNICODE_STRING uPath;
    BrokerInitUnicodeString(&uPath, szNtPath);
    BROKER_OBJECT_ATTRIBUTES oa;
    BROKER_INIT_OA(&oa, &uPath, pReq->ObjAttributes | OBJ_CASE_INSENSITIVE);

    BROKER_UNICODE_STRING uClass;
    BROKER_UNICODE_STRING* pClass = nullptr;
    if (szClass) {
        BrokerInitUnicodeString(&uClass, szClass);
        pClass = &uClass;
    }

    HANDLE hKey = nullptr;
    ULONG disposition = 0;

    // Impersonate and create
    if (!ImpersonateLoggedOnUser(m_hBrokerToken))
        { pRespHeader->dwStatus = (DWORD)BrokerWin32ToNtStatus(GetLastError()); return pRespHeader->dwStatus; }

    NTSTATUS ntStatus = s_NtCreateKey(&hKey, pReq->DesiredAccess, &oa,
                                       pReq->TitleIndex, pClass, pReq->CreateOptions,
                                       &disposition);

    RevertToSelf();

    DWORD fStatus = NtToDosError(ntStatus);
    if (fStatus != ERROR_SUCCESS) {
        pRespHeader->dwStatus = (DWORD)ntStatus;
        return fStatus;
    }

    // Duplicate the key handle into the caller's process
    HANDLE hCallerProcess = OpenProcess(PROCESS_DUP_HANDLE, FALSE, dwCallerPid);
    if (!hCallerProcess) {
        fStatus = GetLastError();
        CloseHandle(hKey);
        pRespHeader->dwStatus = (DWORD)BrokerWin32ToNtStatus(fStatus);
        return fStatus;
    }

    HANDLE hDup = nullptr;
    if (!DuplicateHandle(GetCurrentProcess(), hKey, hCallerProcess, &hDup,
                         0, FALSE, DUPLICATE_SAME_ACCESS))
        fStatus = GetLastError();

    CloseHandle(hKey);
    CloseHandle(hCallerProcess);

    pRespHeader->dwTotalSize = sizeof(BrokerResponseHeader) + sizeof(CreateRegResponsePayload);
    pRespHeader->dwRequestId = dwRequestId;
    pRespHeader->dwStatus    = (DWORD)BrokerWin32ToNtStatus(fStatus);
    pRespHeader->dwHandle    = (DWORD_PTR)hDup;

    auto* pRespPayload = reinterpret_cast<CreateRegResponsePayload*>(pResp + sizeof(BrokerResponseHeader));
    pRespPayload->Disposition = disposition;
    dwRespSize = sizeof(BrokerResponseHeader) + sizeof(CreateRegResponsePayload);

    return fStatus;
}

DWORD Broker::HandleOpenProcess(const BYTE* pPayload, DWORD dwPayloadSize, DWORD dwRequestId,
                                DWORD dwCallerPid, BYTE* pResp, DWORD, DWORD& dwRespSize) {
    auto* pRespHeader = reinterpret_cast<BrokerResponseHeader*>(pResp);

    if (dwPayloadSize < sizeof(OpenProcessRequestPayload))
        { pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER; return ERROR_INVALID_PARAMETER; }

    auto* pReq = reinterpret_cast<const OpenProcessRequestPayload*>(pPayload);

    // Policy check — use PID as a string for the path pattern
    WCHAR szPidStr[32];
    swprintf_s(szPidStr, _countof(szPidStr), L"%lu", pReq->dwTargetProcessId);

    if (!m_policy.IsAllowed(BROKER_OP_OPEN_PROCESS, szPidStr)) {
        pRespHeader->dwStatus = (DWORD)STATUS_ACCESS_DENIED;
        return ERROR_ACCESS_DENIED;
    }

    if (!ImpersonateLoggedOnUser(m_hBrokerToken))
        { pRespHeader->dwStatus = (DWORD)BrokerWin32ToNtStatus(GetLastError()); return pRespHeader->dwStatus; }

    HANDLE hTarget = OpenProcess(pReq->dwDesiredAccess, FALSE, pReq->dwTargetProcessId);
    DWORD fStatus = hTarget ? ERROR_SUCCESS : GetLastError();

    RevertToSelf();

    if (fStatus != ERROR_SUCCESS) {
        pRespHeader->dwStatus = (DWORD)BrokerWin32ToNtStatus(fStatus);
        return fStatus;
    }

    // Duplicate into caller
    HANDLE hCallerProcess = OpenProcess(PROCESS_DUP_HANDLE, FALSE, dwCallerPid);
    if (!hCallerProcess) {
        fStatus = GetLastError();
        CloseHandle(hTarget);
        pRespHeader->dwStatus = (DWORD)BrokerWin32ToNtStatus(fStatus);
        return fStatus;
    }

    HANDLE hDup = nullptr;
    if (!DuplicateHandle(GetCurrentProcess(), hTarget, hCallerProcess, &hDup,
                         0, FALSE, DUPLICATE_SAME_ACCESS))
        fStatus = GetLastError();

    CloseHandle(hTarget);
    CloseHandle(hCallerProcess);

    pRespHeader->dwTotalSize = sizeof(BrokerResponseHeader);
    pRespHeader->dwRequestId = dwRequestId;
    pRespHeader->dwStatus    = (DWORD)BrokerWin32ToNtStatus(fStatus);
    pRespHeader->dwHandle    = (DWORD_PTR)hDup;
    dwRespSize = sizeof(BrokerResponseHeader);

    return fStatus;
}

DWORD Broker::HandleTrace(const BYTE* pPayload, DWORD dwPayloadSize, DWORD dwRequestId,
                          DWORD dwCallerPid, BYTE* pResp, DWORD, DWORD& dwRespSize) {
    auto* pRespHeader = reinterpret_cast<BrokerResponseHeader*>(pResp);

    if (dwPayloadSize < offsetof(TraceRequestPayload, szMessage)) {
        pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER;
        return ERROR_INVALID_PARAMETER;
    }

    auto* pReq = reinterpret_cast<const TraceRequestPayload*>(pPayload);
    if (pReq->dwMessageLengthBytes == 0 ||
        pReq->dwMessageLengthBytes > dwPayloadSize - offsetof(TraceRequestPayload, szMessage)) {
        pRespHeader->dwStatus = (DWORD)STATUS_INVALID_PARAMETER;
        return ERROR_INVALID_PARAMETER;
    }

    DWORD msgLen = pReq->dwMessageLengthBytes;
    char message[1024] = {};
    size_t copyLen = msgLen < sizeof(message) ? msgLen : sizeof(message) - 1;
    memcpy(message, pReq->szMessage, copyLen);
    message[copyLen] = '\0';

    char fullMessage[1200] = {};
    sprintf_s(fullMessage, "Broker trace from pid=%lu: %s", dwCallerPid, message);
    IssueMessage(fullMessage, MSGTYPE_INFO);

    pRespHeader->dwTotalSize = sizeof(BrokerResponseHeader);
    pRespHeader->dwRequestId = dwRequestId;
    pRespHeader->dwStatus    = ERROR_SUCCESS;
    pRespHeader->dwHandle    = 0;
    dwRespSize = sizeof(BrokerResponseHeader);

    return ERROR_SUCCESS;
}
